Traceback (most recent call last):
  File "c:\users\vikram\pokemon_ai\showdown_ai\showdown.py", line 192, in run
    self.play_game(challenge=challenge)
  File "c:\users\vikram\pokemon_ai\showdown_ai\showdown.py", line 171, in play_game
    self.selenium.switch(move.switch_index, move.backup_switch)
  File "c:\users\vikram\pokemon_ai\showdown_ai\browser.py", line 181, in switch
    buttons[i].click()
IndexError: list index out of range
