Traceback (most recent call last):
  File "c:\users\vikram\pokemon_ai\showdown_ai\showdown.py", line 258, in run
    self.play_game(challenge=challenge)
  File "c:\users\vikram\pokemon_ai\showdown_ai\showdown.py", line 222, in play_game
    gamestate = self.create_initial_gamestate()
  File "c:\users\vikram\pokemon_ai\showdown_ai\showdown.py", line 110, in create_initial_gamestate
    opp_pokes.primary_poke = opp_primary
UnboundLocalError: local variable 'opp_primary' referenced before assignment
